from django.conf import settings
from django.db import models
from django.utils import timezone


class HusbandrySettings(models.Model):
    """Per-farm dairy-husbandry timing defaults (female-focused)."""

    farm = models.OneToOneField(
        'farm.Farm',
        on_delete=models.CASCADE,
        related_name='husbandry_settings',
    )
    gestation_days = models.PositiveIntegerField(default=280)
    voluntary_waiting_days = models.PositiveIntegerField(default=60)
    dry_period_days = models.PositiveIntegerField(default=60)
    lactation_target_days = models.PositiveIntegerField(default=305)
    estrous_cycle_days = models.PositiveIntegerField(default=21)
    pregnancy_check_days = models.PositiveIntegerField(
        default=35,
        help_text='Days after breeding to schedule pregnancy check.',
    )
    weaning_days = models.PositiveIntegerField(default=90)
    first_breeding_age_days = models.PositiveIntegerField(
        default=450,
        help_text='Typical heifer first breeding age (~15 months).',
    )
    fresh_monitor_days = models.PositiveIntegerField(default=21)
    calving_prep_days = models.PositiveIntegerField(
        default=14,
        help_text='Days before expected calving to prep.',
    )
    heat_watch_days = models.PositiveIntegerField(
        default=7,
        help_text='Heat observation window length around breeding eligibility.',
    )
    task_alert_lead_days = models.PositiveIntegerField(
        default=7,
        help_text='Create alerts this many days before a task is due.',
    )
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'husbandry settings'
        verbose_name_plural = 'husbandry settings'

    def __str__(self):
        return f'Husbandry settings — {self.farm.name}'

    @classmethod
    def load(cls, farm):
        obj, _ = cls.objects.get_or_create(farm=farm)
        return obj


class HusbandryTask(models.Model):
    class TaskType(models.TextChoices):
        WEANING = 'WEANING', 'Weaning'
        FIRST_BREEDING = 'FIRST_BREEDING', 'First breeding eligible'
        HEAT_WATCH = 'HEAT_WATCH', 'Heat watch'
        BREEDING = 'BREEDING', 'Breeding / AI due'
        PREGNANCY_CHECK = 'PREGNANCY_CHECK', 'Pregnancy check'
        DRY_OFF = 'DRY_OFF', 'Dry-off'
        CALVING_PREP = 'CALVING_PREP', 'Calving preparation'
        CALVING = 'CALVING', 'Expected calving'
        FRESH_MONITOR = 'FRESH_MONITOR', 'Fresh cow monitoring'
        REBREEDING = 'REBREEDING', 'Rebreeding eligible (VWP end)'
        LACTATION_CHECK = 'LACTATION_CHECK', 'Lactation review'
        VACCINATION = 'VACCINATION', 'Vaccination due'

    class Status(models.TextChoices):
        PENDING = 'PENDING', 'Pending'
        COMPLETED = 'COMPLETED', 'Completed'
        SKIPPED = 'SKIPPED', 'Skipped'
        CANCELLED = 'CANCELLED', 'Cancelled'

    class Priority(models.TextChoices):
        LOW = 'LOW', 'Low'
        NORMAL = 'NORMAL', 'Normal'
        HIGH = 'HIGH', 'High'
        CRITICAL = 'CRITICAL', 'Critical'

    farm = models.ForeignKey(
        'farm.Farm',
        on_delete=models.CASCADE,
        related_name='husbandry_tasks',
    )
    cattle = models.ForeignKey(
        'cattle.Cattle',
        on_delete=models.CASCADE,
        related_name='husbandry_tasks',
    )
    task_type = models.CharField(max_length=32, choices=TaskType.choices)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    due_date = models.DateField()
    status = models.CharField(
        max_length=16,
        choices=Status.choices,
        default=Status.PENDING,
    )
    priority = models.CharField(
        max_length=16,
        choices=Priority.choices,
        default=Priority.NORMAL,
    )
    is_auto = models.BooleanField(
        default=True,
        help_text='Generated by the husbandry engine.',
    )
    source_key = models.CharField(
        max_length=191,
        help_text='Idempotent key for auto-generated tasks.',
    )
    related_breeding = models.ForeignKey(
        'breeding.BreedingEvent',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='husbandry_tasks',
    )
    related_pregnancy = models.ForeignKey(
        'breeding.Pregnancy',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='husbandry_tasks',
    )
    completed_at = models.DateTimeField(null=True, blank=True)
    completed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='completed_husbandry_tasks',
    )
    completion_notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['due_date', 'priority']
        constraints = [
            models.UniqueConstraint(
                fields=['farm', 'source_key'],
                name='uniq_husbandry_farm_source_key',
            ),
        ]
        indexes = [
            models.Index(fields=['farm', 'status', 'due_date']),
            models.Index(fields=['cattle', 'status']),
            models.Index(fields=['task_type', 'due_date']),
        ]

    def __str__(self):
        return f'{self.cattle.tag_id}: {self.title} ({self.due_date})'

    @property
    def days_until(self):
        return (self.due_date - timezone.localdate()).days

    @property
    def is_overdue(self):
        return (
            self.status == self.Status.PENDING
            and self.due_date < timezone.localdate()
        )

    def mark_completed(self, user=None, notes=''):
        self.status = self.Status.COMPLETED
        self.completed_at = timezone.now()
        self.completed_by = user
        if notes:
            self.completion_notes = notes
        self.save(
            update_fields=[
                'status',
                'completed_at',
                'completed_by',
                'completion_notes',
                'updated_at',
            ]
        )
