# Generated by Django 6.0.7 on 2026-07-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sire_external_id', models.CharField(blank=True, max_length=128)),
                ('mating_date', models.DateField()),
                ('method', models.CharField(choices=[('NATURAL', 'Natural'), ('AI', 'Artificial Insemination')], default='NATURAL', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_as_dam', to='cattle.cattle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_events', to='farm.farm')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeding_as_sire', to='cattle.cattle')),
            ],
            options={
                'ordering': ['-mating_date'],
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_on', models.DateField(blank=True, null=True)),
                ('expected_calving_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PREGNANT', 'Pregnant'), ('CALVED', 'Calved'), ('FAILED', 'Failed')], default='PREGNANT', max_length=16)),
                ('clinical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breeding_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregnancies', to='breeding.breedingevent')),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='cattle.cattle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='farm.farm')),
            ],
            options={
                'verbose_name_plural': 'pregnancies',
                'ordering': ['-expected_calving_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BirthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calving_date', models.DateField()),
                ('calf_tag_id', models.CharField(blank=True, max_length=64)),
                ('calf_sex', models.CharField(blank=True, max_length=10)),
                ('complications', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_record', to='cattle.cattle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_records', to='farm.farm')),
                ('pregnancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth', to='breeding.pregnancy')),
            ],
            options={
                'ordering': ['-calving_date'],
            },
        ),
        migrations.AddIndex(
            model_name='breedingevent',
            index=models.Index(fields=['farm', 'mating_date'], name='breeding_br_farm_id_d7da35_idx'),
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['farm', 'status'], name='breeding_pr_farm_id_a94b19_idx'),
        ),
        migrations.AddIndex(
            model_name='birthrecord',
            index=models.Index(fields=['farm', 'calving_date'], name='breeding_bi_farm_id_ed23c3_idx'),
        ),
    ]
