# Generated by Django 6.0.7 on 2026-07-26 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
        ('milk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=16)),
                ('category', models.CharField(choices=[('milk_production', 'Milk production income'), ('milk_sale', 'Milk cash sale'), ('feed', 'Feed'), ('vet', 'Veterinary'), ('labor', 'Labor'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ETB', max_length=8)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_auto', models.BooleanField(default=False, help_text='Generated automatically (e.g. milk production valuation).')),
                ('source_key', models.CharField(blank=True, default=None, help_text='Idempotent key for auto transactions.', max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='farm.farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('related_milk_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='milk.milkrecord')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['farm', 'date', 'type'], name='finance_tra_farm_id_4cd667_idx'), models.Index(fields=['farm', 'is_auto', 'date'], name='finance_tra_farm_id_8cc93d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_key__isnull', False)), fields=('farm', 'source_key'), name='uniq_txn_farm_source_key')],
            },
        ),
    ]
