# Generated by Django 6.0.7 on 2026-07-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('milk_production', 'Milk production income'), ('milk_sale', 'Milk cash sale'), ('cattle_sale', 'Cattle sale income'), ('feed', 'Feed'), ('vet', 'Veterinary'), ('labor', 'Labor'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
