# Generated by Django 6.0.7 on 2026-07-26 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=128)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=32)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cost booked as a feed expense.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_schedules', to='cattle.cattle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_schedules', to='farm.farm')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['farm', 'date'], name='milk_feedsc_farm_id_a6fa87_idx')],
            },
        ),
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_liters', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('evening_liters', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='cattle.cattle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='farm.farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'cattle_id'],
                'indexes': [models.Index(fields=['farm', 'date'], name='milk_milkre_farm_id_4d31a1_idx'), models.Index(fields=['cattle', 'date'], name='milk_milkre_cattle__17bcba_idx')],
                'unique_together': {('cattle', 'date')},
            },
        ),
    ]
