# Generated by Django 6.0.7 on 2026-07-26 09:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('woreda', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('milk_price_per_liter', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Farm-gate price per liter (ETB by default).', max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=8)),
                ('milk_income_mode', models.CharField(choices=[('ACCRUAL', 'Accrual (value production)'), ('CASH', 'Cash (sales only)')], default='ACCRUAL', help_text='ACCRUAL books daily production as income (cash sales tracked separately). CASH only counts milk cash sales toward profit.', max_length=16)),
                ('auto_milk_income', models.BooleanField(default=True, help_text='When enabled (and mode is ACCRUAL), daily milk production creates income rows.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
