# Generated by Django 6.0.7 on 2026-07-26 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MILK', 'Milk'), ('HEALTH', 'Health'), ('BREEDING', 'Breeding'), ('FINANCE', 'Finance'), ('SYSTEM', 'System')], max_length=16)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='cattle.cattle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farm.farm')),
                ('user', models.ForeignKey(blank=True, help_text='Null = visible to role-filtered inbox for all relevant users on the farm.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', 'category', 'is_read'], name='alerts_aler_farm_id_bdbfee_idx'), models.Index(fields=['farm', 'created_at'], name='alerts_aler_farm_id_dc8c41_idx'), models.Index(fields=['farm', 'dedupe_key'], name='alerts_aler_farm_id_b8707f_idx')],
            },
        ),
    ]
