# Generated by Django 6.0.7 on 2026-07-26 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeding', '0001_initial'),
        ('cattle', '0001_initial'),
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HusbandrySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestation_days', models.PositiveIntegerField(default=280)),
                ('voluntary_waiting_days', models.PositiveIntegerField(default=60)),
                ('dry_period_days', models.PositiveIntegerField(default=60)),
                ('lactation_target_days', models.PositiveIntegerField(default=305)),
                ('estrous_cycle_days', models.PositiveIntegerField(default=21)),
                ('pregnancy_check_days', models.PositiveIntegerField(default=35, help_text='Days after breeding to schedule pregnancy check.')),
                ('weaning_days', models.PositiveIntegerField(default=90)),
                ('first_breeding_age_days', models.PositiveIntegerField(default=450, help_text='Typical heifer first breeding age (~15 months).')),
                ('fresh_monitor_days', models.PositiveIntegerField(default=21)),
                ('calving_prep_days', models.PositiveIntegerField(default=14, help_text='Days before expected calving to prep.')),
                ('heat_watch_days', models.PositiveIntegerField(default=7, help_text='Heat observation window length around breeding eligibility.')),
                ('task_alert_lead_days', models.PositiveIntegerField(default=7, help_text='Create alerts this many days before a task is due.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='husbandry_settings', to='farm.farm')),
            ],
            options={
                'verbose_name': 'husbandry settings',
                'verbose_name_plural': 'husbandry settings',
            },
        ),
        migrations.CreateModel(
            name='HusbandryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('WEANING', 'Weaning'), ('FIRST_BREEDING', 'First breeding eligible'), ('HEAT_WATCH', 'Heat watch'), ('BREEDING', 'Breeding / AI due'), ('PREGNANCY_CHECK', 'Pregnancy check'), ('DRY_OFF', 'Dry-off'), ('CALVING_PREP', 'Calving preparation'), ('CALVING', 'Expected calving'), ('FRESH_MONITOR', 'Fresh cow monitoring'), ('REBREEDING', 'Rebreeding eligible (VWP end)'), ('LACTATION_CHECK', 'Lactation review'), ('VACCINATION', 'Vaccination due')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=16)),
                ('is_auto', models.BooleanField(default=True, help_text='Generated by the husbandry engine.')),
                ('source_key', models.CharField(help_text='Idempotent key for auto-generated tasks.', max_length=191)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husbandry_tasks', to='cattle.cattle')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_husbandry_tasks', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husbandry_tasks', to='farm.farm')),
                ('related_breeding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='husbandry_tasks', to='breeding.breedingevent')),
                ('related_pregnancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='husbandry_tasks', to='breeding.pregnancy')),
            ],
            options={
                'ordering': ['due_date', 'priority'],
                'indexes': [models.Index(fields=['farm', 'status', 'due_date'], name='husbandry_h_farm_id_7f46a4_idx'), models.Index(fields=['cattle', 'status'], name='husbandry_h_cattle__b94264_idx'), models.Index(fields=['task_type', 'due_date'], name='husbandry_h_task_ty_b8546a_idx')],
                'constraints': [models.UniqueConstraint(fields=('farm', 'source_key'), name='uniq_husbandry_farm_source_key')],
            },
        ),
    ]
