# Generated by Django 6.0.7 on 2026-07-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('breed', models.CharField(blank=True, max_length=128)),
                ('sex', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], default='FEMALE', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('DEAD', 'Dead'), ('CULLED', 'Culled')], default='ACTIVE', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('photo_front', models.ImageField(blank=True, help_text='Front view for identification.', null=True, upload_to='cattle/front/')),
                ('photo_left', models.ImageField(blank=True, help_text='Left side view.', null=True, upload_to='cattle/left/')),
                ('photo_right', models.ImageField(blank=True, help_text='Right side view.', null=True, upload_to='cattle/right/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cattle', to='farm.farm')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_father', to='cattle.cattle')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_mother', to='cattle.cattle')),
            ],
            options={
                'verbose_name_plural': 'cattle',
                'ordering': ['tag_id'],
                'indexes': [models.Index(fields=['farm', 'status'], name='cattle_catt_farm_id_2994f0_idx'), models.Index(fields=['farm', 'tag_id'], name='cattle_catt_farm_id_8bd201_idx')],
                'constraints': [models.UniqueConstraint(fields=('farm', 'tag_id'), name='uniq_cattle_farm_tag')],
            },
        ),
    ]
