# Generated by Django 6.0.7 on 2026-07-29 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0001_initial'),
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='cull_reason',
            field=models.CharField(blank=True, help_text='Reason for culling (e.g. low fertility, chronic mastitis, old age).', max_length=255),
        ),
        migrations.AddField(
            model_name='cattle',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price when animal is sold.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='CattleGrowthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Body weight in kg.', max_digits=6, null=True)),
                ('bcs', models.DecimalField(blank=True, decimal_places=2, help_text='Body Condition Score (1.00 to 5.00 standard dairy scale).', max_digits=3, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_logs', to='cattle.cattle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_logs', to='farm.farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['farm', 'date'], name='cattle_catt_farm_id_4664c0_idx'), models.Index(fields=['cattle', 'date'], name='cattle_catt_cattle__c395b7_idx')],
            },
        ),
    ]
