# Generated by Django 6.0.7 on 2026-07-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_cattle_cull_reason_cattle_sale_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='father_external_id',
            field=models.CharField(blank=True, help_text='Info if father is not in the system.', max_length=128),
        ),
        migrations.AddField(
            model_name='cattle',
            name='mother_external_id',
            field=models.CharField(blank=True, help_text='Info if mother is not in the system.', max_length=128),
        ),
    ]
