# Generated by Django 6.0.7 on 2026-07-26 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cattle.cattle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='farm.farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['farm', 'recorded_at'], name='health_heal_farm_id_82dd3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255)),
                ('medication', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('veterinarian_name', models.CharField(blank=True, max_length=128)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cost booked as a veterinary expense.', max_digits=12, null=True)),
                ('outcome', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='cattle.cattle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='farm.farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['farm', 'start_date'], name='health_trea_farm_id_cd5bdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=128)),
                ('administered_on', models.DateField()),
                ('next_due_on', models.DateField(blank=True, null=True)),
                ('veterinarian_name', models.CharField(blank=True, max_length=128)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cost booked as a veterinary expense.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='cattle.cattle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='farm.farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-administered_on'],
                'indexes': [models.Index(fields=['farm', 'next_due_on'], name='health_vacc_farm_id_15a1df_idx')],
            },
        ),
    ]
